### ISSUE TITLE
Some files (ollama_query.py) in utils are missing

### ISSUE THREAD

**Issue by hansen7** [idekerlab/llm_evaluation_for_gene_set_interpretation#56]
![image](https://github.com/idekerlab/llm_evaluation_for_gene_set_interpretation/assets/14752739/3e8c09af-95ea-4329-adf1-fea24ecb8f9a)

**Comment by Clarararaara** [comment]
Thank you for the heads up. We had recent updates to the repo and is now available on the main branch.

**Comment by hansen7** [comment]
Thank you!
